### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by theshyyi** [thieu1995/enoppy#2]
### Description of the bug

Hello, when I use enoppy and run according to one of the examples I get the following error, I don't know how to change my code to work properly, please advise me.
![image](https://github.com/thieu1995/enoppy/assets/59169927/d53fe0e5-bc0c-4dc9-996e-9b5fd4545846)
![image](https://github.com/thieu1995/enoppy/assets/59169927/9e9df2ea-b219-48e9-98ab-ea654b652d30)

### Steps To Reproduce

    model = SMA.BaseSMA(problem_dict1,epoch=50,pop_size=30,p_t= 0.03)
TypeError: __init__() got multiple values for argument 'epoch'

**Comment by thieu1995** [comment]
Hi @theshyyi ,

I think you are using latest version of mealpy version 3.0.1. 
However, the example above is for mealpy version 2.5.4. So you should revert it back by:

`pip install mealpy==2.5.4`

Or you can update the code to version 3.0.1. Check out the document of mealpy.

```python
from mealpy import FloatVar, SMA
from enoppy.paper_based import moeosma_2023

prob = moeosma_2023.SpeedReducerProblem()

problem = {
    "obj_func": prob.evaluate,
    "bounds": FloatVar(lb=prob.lb, ub=prob.ub),
    "minmax": "min",
    "log_to": "console",
}

## Run the algorithm
model = SMA.OriginalSMA(epoch=100, pop_size=50, pr=0.03)
g_best = model.solve(problem)
print(f"Best solution: {g_best.solution}, Best fitness: {g_best.target.fitness}")
```

**Comment by theshyyi** [comment]
Thanks for the reply, but a new error was reported after modifying it the way you did.I can't understand it at the moment.
![image](https://github.com/thieu1995/enoppy/assets/59169927/9ea34cc0-a71a-4fb6-bd29-4517597be060)

**Comment by thieu1995** [comment]
It is very clear that the Speed Reducer Problem is multi-objective optimization problem (2 objectives). 
So you have to set obj_weights as a list with weighting factors. For example.

```
problem = {
    "obj_func": prob.evaluate,
    "bounds": FloatVar(lb=prob.lb, ub=prob.ub),
    "minmax": "min",
    "log_to": "console",
    "obj_weights": [0.5, 0.5],
}
```

**Comment by theshyyi** [comment]
Wow, that's amazing, as a novice it gave you trouble, thanks for clearing that up.

**Comment by thieu1995** [comment]
That is okay, everyone has to start somewhere.
