### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by theshyyi** [thieu1995/enoppy#3]
### Description of the bug

Hello again, I'm using Enoppy and the results I get when the calculation is completed do not match the results I get when I use the formula, is there something wrong with that parameter?
![image](https://github.com/thieu1995/enoppy/assets/59169927/18afcec2-3756-4755-bc0d-fe8aa28821d6)
![image](https://github.com/thieu1995/enoppy/assets/59169927/3c36a870-5d91-4c94-9cef-e783822e685a)
![image](https://github.com/thieu1995/enoppy/assets/59169927/8c644934-368f-42e7-95cf-316a48e4e003)
![image](https://github.com/thieu1995/enoppy/assets/59169927/5d5e6ece-8b7e-4c13-99e7-a40d16ebd4ad)
You see that the optimal solution according to the computer output is 18928953.71308417, but the optimal solution according to the formula should be 0.3184176.

### Steps To Reproduce

You see that the optimal solution according to the computer output is 18928953.71308417, but the optimal solution according to the formula should be 0.3184176. 
I found out that there is a parameter w = 1e8 in engineer.py, and this parameter has a big impact on the result of the calculation. I don't know how to adjust my code. I hope you can help me out, thank you very much!

**Comment by thieu1995** [comment]
These problems are hard problems. So the given solution above is actually not valid, that is why the value is so big. Because it got penaltized by invalid solution. So you should try more algorithms.

**Comment by theshyyi** [comment]
Thank you very much. I get it.
